// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DB.Models
{
    public partial class ChildrenTimeLine
    {
        public long ChildrenTimeLineId { get; set; }
        public long ChildrenId { get; set; }
        public string Height { get; set; }
        public string Weight { get; set; }
        public DateTime TimeLineDate { get; set; }
        public string Vaccine { get; set; }
        public string TreatmentType { get; set; }
        public string Description { get; set; }
        public string FilePath { get; set; }
        public int? ChildAge { get; set; }

        public virtual Children Children { get; set; }
    }
}