// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DB.Models
{
    public partial class ForumRelation
    {
        public long ForumRelationId { get; set; }
        public long ForumAnswerId { get; set; }
        public long MainForumId { get; set; }

        public virtual ForumAnswer ForumAnswer { get; set; }
        public virtual MainForum MainForum { get; set; }
    }
}