// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DB.Models
{
    public partial class ForumAnswer
    {
        public ForumAnswer()
        {
            ForumRelation = new HashSet<ForumRelation>();
        }

        public long ForumAnswerId { get; set; }
        public long UserId { get; set; }
        public string ForumAnswer1 { get; set; }
        public DateTime? ForumAnswerDate { get; set; }

        public virtual Users User { get; set; }
        public virtual ICollection<ForumRelation> ForumRelation { get; set; }
    }
}