// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DB.Models
{
    public partial class MainForum
    {
        public MainForum()
        {
            ForumRelation = new HashSet<ForumRelation>();
        }

        public long MainForumId { get; set; }
        public long UserId { get; set; }
        public string MainForumTitle { get; set; }
        public string MainForumMessage { get; set; }
        public DateTime? MainForumDate { get; set; }

        public virtual Users User { get; set; }
        public virtual ICollection<ForumRelation> ForumRelation { get; set; }
    }
}