// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DB.Models
{
    public partial class Users
    {
        public Users()
        {
            Children = new HashSet<Children>();
            ForumAnswer = new HashSet<ForumAnswer>();
            MainForum = new HashSet<MainForum>();
        }

        public long UserId { get; set; }
        public string UserFullName { get; set; }
        public string UserEmail { get; set; }
        public string UserPassword { get; set; }
        public bool? IsDoctor { get; set; }
        public string UserFilePath { get; set; }

        public virtual ICollection<Children> Children { get; set; }
        public virtual ICollection<ForumAnswer> ForumAnswer { get; set; }
        public virtual ICollection<MainForum> MainForum { get; set; }
    }
}